version: '3'
services:
  api:
    container_name: places-api
    image: places-api:1.0.0
    environment:
      - elastic-uri=http://esearch:9200
    ports:
      - "6800:80"
    depends_on:
      - esearch

  esearch:
    container_name: esearch
    image: elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-s:/usr/share/elasticsearch/data
    ports:
      - "4455:9200"
volumes:
  elastic-s:
    external: true
    name: elastic-s
