version: "3"
services:
  api:
    container_name: places-api
    image: places-api:1.0.0
    environment:
      - elastic-uri=http://esearch:9200
    depends_on:
      - esearch
    ports:
      - "6692:80"

  places-presentation:
    container_name: places-presentation
    image: places-presentation:1.0.0
    ports:
      - "3100:80"
    depends_on:
      - api
      - esearch
    volumes:
      - places-presentation:/etc/nginx/

  esearch:
    container_name: esearch
    image: elasticsearch:7.6.2
    environment:
      - discovery.type=single-node
    volumes:
      - elastic-s:/usr/share/elasticsearch/data

volumes:
  elastic-s:
    external: true
    name: elastic-s
  places-presentation:
    external: true
    name: places-presentation
